title: Keypoint Detection
log_level: 2
inputs:
  input0:
    source: /dev/video-usb-cam0
    format: jpeg
    width: 1280
    height: 720
    framerate: 30
models:
  model0:
    model_path: /opt/model_zoo/ONR-KD-7060-human-pose-yolox-s-640x640
    viz-threshold: 0.5
outputs:
  output0:
    sink: remote
    host: 127.0.0.1
    port: 8081
    width: 1280
    height: 720
    encoding: jpeg
    bitrate: 1000000
flows:
  flow0:
  - input0
  - model0
  - output0
