title: Object Detection
log_level: 2
inputs:
  input0:
    source: None
    format: None
    width: 0
    height: 0
    framerate: 30
    subdev-id: None
    sen-id: None
    ldc: None
    index: 0
    loop: True
models:
  model0:
    model_path: /opt/model_zoo/TFL-OD-2020-ssdLite-mobDet-DSP-coco-320x320
    viz_threshold: 0.6
outputs:
  output0:
    sink: remote
    host: 127.0.0.1
    port: 8081
    width: 1280
    height: 720
    encoding: jpeg
    bitrate: 1000000
flows:
  flow0:
  - input0
  - model0
  - output0
