title: Object Detection Demo
log_level: 2
inputs:
  input0:
    source: /dev/video2
    format: jpeg
    width: 640
    height: 360
    framerate: 30
models:
  model0:
    model_path: /opt/model_zoo/TFL-OD-2020-ssdLite-mobDet-DSP-coco-320x320
    viz_threshold: 0.6
outputs:
  output0:
    sink: remote
    host: 127.0.0.1
    port: 8081
    width: 640
    height: 360
    payloader: mp4mux
    bitrate: 1000000
flows:
  flow0:
  - input0
  - model0
  - output0
