title: Semantic Segmentation
log_level: 2
inputs:
  input0:
    source: /dev/video-usb-cam0
    format: jpeg
    width: 1280
    height: 720
    framerate: 30
models:
  model0:
    model_path: /opt/model_zoo/ONR-SS-8610-deeplabv3lite-mobv2-ade20k32-512x512
    alpha: 0.2
outputs:
  output0:
    sink: remote
    host: 127.0.0.1
    port: 8081
    width: 1280
    height: 720
    encoding: jpeg
    bitrate: 1000000
flows:
  flow0:
  - input0
  - model0
  - output0
